"use client";
import {useEffect,useRef,useState} from "react";
import {motion} from "framer-motion";
import Link from "next/link";
import {ArrowLeft,Bot,File,Paperclip,Send,Sparkles,Users} from "lucide-react";
import {api,getUser,type AuthUser} from "@/lib/auth";
type Message={message_id:string;group_id:string;sender_id:string;message_type:"text"|"image"|"file"|"video";text?:string|null;media_url?:string|null;file_name?:string|null;created_at:string};
type Group={group_id:string;name:string;owner_id:string;member_ids:string[];created_at:string;updated_at:string};
export default function GroupPage({params}:{params:Promise<{groupId:string}>}){
 const [groupId,setGroupId]=useState(""),[user,setUser]=useState<AuthUser|null>(null),[group,setGroup]=useState<Group|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[connected,setConnected]=useState(false),[aiPrompt,setAiPrompt]=useState("");
 const ws=useRef<WebSocket|null>(null),bottom=useRef<HTMLDivElement|null>(null),apiBase=api.url.replace(/\/api\/?$/,""),wsBase=api.url.replace(/^http/,"ws").replace(/\/api\/?$/,"");
 useEffect(()=>{params.then(p=>setGroupId(p.groupId))},[params]);useEffect(()=>{const u=getUser();setUser(u);if(!u)location.href="/login"},[]);
 useEffect(()=>{if(!groupId||!user)return;let active=true;(async()=>{const r=await api.fetch(`/study-groups/${groupId}?user_id=${encodeURIComponent(user.user_id)}`);if(r.ok&&active)setGroup(await r.json());const r=await api.fetch(`/study-groups/${groupId}/messages?user_id=${encodeURIComponent(user.user_id)}&skip=0&limit=100`);if(r.ok&&active)setMessages(await r.json());const s=new WebSocket(`${wsBase}/api/study-groups/${groupId}/ws?user_id=${encodeURIComponent(user.user_id)}`);ws.current=s;s.onopen=()=>setConnected(true);s.onclose=()=>setConnected(false);s.onmessage=e=>{const m=JSON.parse(e.data) as Message;setMessages(v=>[...v.filter(x=>x.message_id!==m.message_id),m])}})();return()=>{active=false;ws.current?.close()}},[groupId,user,wsBase]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function send(){if(!user||!text.trim())return;const r=await api.fetch(`/study-groups/${groupId}/messages/text`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sender_id:user.user_id,text:text.trim()})});if(r.ok)setText("")}
 async function upload(file:File){if(!user)return;const f=new FormData();f.append("file",file);const r=await api.fetch(`/study-groups/${groupId}/messages/media?sender_id=${encodeURIComponent(user.user_id)}`,{method:"POST",body:f});if(!r.ok)alert("Upload failed")}
 const aiActions=["Summarize discussion","Explain the hardest concept","Create 5 revision questions"];
 return <main style={{height:"100vh",display:"grid",gridTemplateRows:"76px 1fr",background:"radial-gradient(circle at 50% 0%,rgba(96,231,255,.06),transparent 24%)"}}>
 <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 22px",borderBottom:"1px solid var(--line)",background:"rgba(5,8,22,.78)",backdropFilter:"blur(20px)"}}><div style={{display:"flex",alignItems:"center",gap:14}}><Link href="/study-groups" style={{display:"flex",alignItems:"center",gap:7,color:"var(--muted)"}}><ArrowLeft size={17}/> Groups</Link><span style={{color:"var(--muted)"}}>/</span><div><div style={{fontFamily:"Space Grotesk",fontWeight:700}}>{group?.name??"Study group"}</div><div style={{fontSize:12,color:connected?"var(--green)":"#ffb26f"}}>{connected?"● live":"○ connecting"}</div></div></div><div style={{display:"flex",gap:8,alignItems:"center",color:"var(--muted)",fontSize:13}}><Users size={16}/>{group?.member_ids.length??"—"} members</div></header>
 <section className="chat-layout" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 340px",minHeight:0}}>
 <div style={{display:"grid",gridTemplateRows:"1fr auto",minHeight:0}}><div style={{padding:"26px 28px",overflow:"auto"}}><div style={{maxWidth:860,margin:"0 auto",display:"grid",gap:14}}>{messages.map(m=><motion.div key={m.message_id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} style={{display:"flex",justifyContent:m.sender_id===user?.user_id?"flex-end":"flex-start"}}><div style={{maxWidth:"78%"}}><div style={{fontSize:11,color:"var(--muted)",marginBottom:4,textAlign:m.sender_id===user?.user_id?"right":"left"}}>{m.sender_id===user?.user_id?"You":m.sender_id}</div><div className="glass" style={{padding:"11px 14px",borderRadius:18}}>{m.message_type==="text"&&<div style={{lineHeight:1.55}}>{m.text}</div>}{m.message_type==="image"&&m.media_url&&<img src={apiBase+m.media_url} alt={m.file_name??"image"} style={{maxWidth:320,borderRadius:12}}/>}{m.message_type==="video"&&m.media_url&&<video controls src={apiBase+m.media_url} style={{maxWidth:360,borderRadius:12}}/>}{m.message_type==="file"&&<a href={apiBase+(m.media_url??"")} target="_blank" style={{display:"flex",gap:9,color:"var(--cyan)"}}><File size={18}/>{m.file_name}</a>}</div></div></motion.div>)}<div ref={bottom}/></div></div>
 <div style={{padding:"16px 20px 20px",borderTop:"1px solid var(--line)",background:"rgba(5,8,22,.78)"}}><div style={{maxWidth:860,margin:"0 auto",display:"flex",gap:10}}><label style={{width:46,height:46,borderRadius:14,display:"grid",placeItems:"center",background:"rgba(255,255,255,.05)",border:"1px solid var(--line)",cursor:"pointer"}}><Paperclip size={18} color="var(--muted)"/><input hidden type="file" accept="image/*,video/*,.pdf,.doc,.docx,.txt,.zip" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message your group…" style={{flex:1,padding:"13px 15px",borderRadius:14,border:"1px solid var(--line)",background:"rgba(255,255,255,.04)",color:"white",outline:"none"}}/><button onClick={send} style={{width:46,borderRadius:14,background:"linear-gradient(135deg,#60e7ff,#8f7cff)"}}><Send size={18}/></button></div></div></div>
 <aside className="ai-panel" style={{borderLeft:"1px solid var(--line)",background:"rgba(8,13,28,.62)",padding:20,display:"grid",gridTemplateRows:"auto auto 1fr",gap:16}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{width:40,height:40,borderRadius:13,display:"grid",placeItems:"center",background:"linear-gradient(135deg,rgba(96,231,255,.16),rgba(143,124,255,.2))"}}><Bot size={21} color="var(--cyan)"/></div><div><b style={{fontFamily:"Space Grotesk"}}>Study AI</b><div style={{fontSize:11,color:"var(--muted)"}}>Group companion</div></div></div><div className="glass" style={{borderRadius:18,padding:15}}><div style={{display:"flex",alignItems:"center",gap:7,color:"var(--cyan)",fontSize:12,fontWeight:700}}><Sparkles size={15}/> AI actions</div><div style={{display:"grid",gap:8,marginTop:12}}>{aiActions.map(a=><button key={a} onClick={()=>setAiPrompt(a)} style={{textAlign:"left",padding:"10px 11px",borderRadius:11,border:"1px solid var(--line)",background:"rgba(255,255,255,.03)",color:"var(--text)",cursor:"pointer"}}>{a}</button>)}</div></div><div style={{display:"grid",gridTemplateRows:"1fr auto",gap:10}}><div className="glass" style={{borderRadius:18,padding:16,color:"var(--muted)",fontSize:14,lineHeight:1.6}}><div style={{color:"var(--text)",fontWeight:700,marginBottom:8}}>AI is ready.</div><p style={{margin:0}}>The collaboration surface is ready for your AI service to consume group context and return summaries, explanations and study plans.</p>{aiPrompt&&<div style={{marginTop:15,padding:11,borderRadius:12,background:"rgba(96,231,255,.05)",border:"1px solid rgba(96,231,255,.12)"}}>{aiPrompt}</div>}</div><div style={{display:"flex",gap:8}}><input value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} placeholder="Ask the study AI…" style={{flex:1,padding:"11px 12px",borderRadius:12,border:"1px solid var(--line)",background:"rgba(255,255,255,.04)",color:"white",outline:"none"}}/><button style={{width:44,borderRadius:12,background:"rgba(96,231,255,.12)",color:"var(--cyan)"}}><Sparkles size={18}/></button></div></div></aside></section></main>}