"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowLeft, Bot, BrainCircuit, File, Paperclip, Send, Sparkles, Users } from "lucide-react";
import { api, getUser, type AuthUser } from "@/lib/auth";

type Message={message_id:string;group_id:string;sender_id:string;message_type:"text"|"image"|"file"|"video";text?:string|null;media_url?:string|null;file_name?:string|null;created_at:string};
type Group={group_id:string;name:string;owner_id:string;member_ids:string[];created_at:string;updated_at:string};
type AiResult={title:string;body:string};

const fallbackNames=["Maya","Arjun","Zoya","Rohan","Priya","Kabir"];

export default function GroupPage({params}:{params:Promise<{groupId:string}>}){
 const [groupId,setGroupId]=useState(""),[user,setUser]=useState<AuthUser|null>(null),[group,setGroup]=useState<Group|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[connected,setConnected]=useState(false),[aiInput,setAiInput]=useState(""),[aiBusy,setAiBusy]=useState(false),[aiResult,setAiResult]=useState<AiResult|null>(null);
 const ws=useRef<WebSocket|null>(null),bottom=useRef<HTMLDivElement|null>(null),apiBase=api.url.replace(/\/api\/?$/,""),wsBase=api.url.replace(/^http/,"ws").replace(/\/api\/?$/,"");
 useEffect(()=>{params.then(p=>setGroupId(p.groupId))},[params]);useEffect(()=>{const u=getUser();if(!u){location.href="/login";return}setUser(u)},[]);
 useEffect(()=>{if(!groupId||!user)return;let active=true;(async()=>{const r=await api.fetch("/study-groups/"+groupId+"?user_id="+encodeURIComponent(user.user_id));if(r.ok&&active)setGroup(await r.json());const m=await api.fetch("/study-groups/"+groupId+"/messages?user_id="+encodeURIComponent(user.user_id)+"&skip=0&limit=100");if(m.ok&&active)setMessages(await m.json());const s=new WebSocket(wsBase+"/api/study-groups/"+groupId+"/ws?user_id="+encodeURIComponent(user.user_id));ws.current=s;s.onopen=()=>setConnected(true);s.onclose=()=>setConnected(false);s.onmessage=e=>{try{const item=JSON.parse(e.data) as Message;setMessages(v=>[...v.filter(x=>x.message_id!==item.message_id),item])}catch{}}})();return()=>{active=false;ws.current?.close()}},[groupId,user,wsBase]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(){if(!user||!text.trim())return;const r=await api.fetch("/study-groups/"+groupId+"/messages/text",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sender_id:user.user_id,text:text.trim()})});if(r.ok)setText("")}
 async function upload(file:File){if(!user)return;const f=new FormData();f.append("file",file);const r=await api.fetch("/study-groups/"+groupId+"/messages/media?sender_id="+encodeURIComponent(user.user_id),{method:"POST",body:f});if(!r.ok)alert("Upload failed")}
 const context=useMemo(()=>messages.filter(m=>m.message_type==="text"&&m.text).map(m=>m.text as string).slice(-30),[messages]);
 function runAi(action:string){setAiBusy(true);setAiResult(null);window.setTimeout(()=>{let body="";if(action==="summary")body=context.length?"The latest discussion contains "+context.length+" text messages. Recent thread: "+context.slice(-5).join(" ")+"\\n\\nStudy AI suggests turning unresolved points into revision notes.":"There is not enough discussion yet. Start chatting and Study AI will build a contextual summary.";else if(action==="questions")body=context.length?Array.from({length:5},(_,i)=>(i+1)+". Explain one important idea from the recent discussion and give a concrete example.").join("\\n"):"Once your group has a discussion, Study AI can turn it into revision questions.";else if(action==="plan")body="25 min — review the latest discussion\\n20 min — write 5 key takeaways\\n20 min — solve 3 questions together\\n10 min — ask Study AI about anything unresolved";else body=aiInput.trim()?"Study AI is using this group's latest "+context.length+" text messages as context.\\n\\nFor “"+aiInput.trim()+"”, identify the concept, connect it to the discussion, then test it with one concrete example.":"Ask a focused question about the current group discussion.";setAiResult({title:action==="summary"?"Discussion brief":action==="questions"?"Revision set":action==="plan"?"Study sprint":"AI response",body});setAiBusy(false)},450)}
 const memberPreview=(group?.member_ids??[]).slice(0,5);
 return <main className="chat-page"><header className="chat-header"><div className="chat-title"><Link href="/study-groups" className="chat-back"><ArrowLeft size={17}/></Link><div className="chat-title-icon"><BrainCircuit size={19}/></div><div><h1>{group?.name??"Study group"}</h1><span><i className={connected?"online-dot":""}/>{connected?"Live collaboration":"Connecting…"}</span></div></div><div className="chat-members">{memberPreview.map((m,i)=><div key={m} title={m} className="member-avatar">{m===user?.user_id?"You":fallbackNames[i%fallbackNames.length][0]}</div>)}<span><Users size={15}/> {group?.member_ids.length??0}</span></div></header>
 <section className="chat-layout"><div className="chat-main"><div className="chat-stream">{messages.length===0&&<div className="chat-empty glass"><BrainCircuit size={34}/><h2>Your study room is ready.</h2><p>Start the discussion. Study AI will use the conversation as context for summaries, questions and study planning.</p></div>}{messages.map(m=><motion.div key={m.message_id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={"message-row "+(m.sender_id===user?.user_id?"mine":"")}><div className="message-avatar">{m.sender_id===user?.user_id?"You":m.sender_id.slice(0,1).toUpperCase()}</div><div className="message-body"><div className="message-meta"><b>{m.sender_id===user?.user_id?"You":m.sender_id}</b><span>{new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><div className="message-bubble">{m.message_type==="text"&&m.text}{m.message_type==="image"&&m.media_url&&<img src={apiBase+m.media_url} alt={m.file_name??"image"}/>} {m.message_type==="video"&&m.media_url&&<video controls src={apiBase+m.media_url}/>} {m.message_type==="file"&&<a href={apiBase+(m.media_url??"")} target="_blank"><File size={17}/>{m.file_name}</a>}</div></div></motion.div>)}<div ref={bottom}/></div><div className="composer"><label className="attach-button"><Paperclip size={18}/><input hidden type="file" accept="image/*,video/*,.pdf,.doc,.docx,.txt,.zip" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message your study group…"/><button onClick={send} disabled={!text.trim()}><Send size={18}/></button></div></div>
 <aside className="ai-panel"><div className="ai-head"><div className="ai-avatar"><Bot size={21}/></div><div><b>Study AI</b><span>Contextual group companion</span></div><span className="ai-live">READY</span></div><div className="ai-context"><Sparkles size={15}/><span>Using latest {context.length} text messages as context</span></div><div className="ai-actions"><button onClick={()=>runAi("summary")}><span>Summarize discussion</span><small>Turn chat into notes</small></button><button onClick={()=>runAi("questions")}><span>Create revision questions</span><small>Practice from the chat</small></button><button onClick={()=>runAi("plan")}><span>Build a study sprint</span><small>Plan the next 75 minutes</small></button></div><div className="ai-result glass">{aiBusy?<div className="ai-thinking"><span/><span/><span/> Thinking with group context…</div>:aiResult?<><div className="ai-result-title">{aiResult.title}</div><p>{aiResult.body}</p></>:<div className="ai-placeholder"><BrainCircuit size={25}/><p>Ask Study AI about the current discussion, or use an action above.</p></div>}</div><div className="ai-ask"><input value={aiInput} onChange={e=>setAiInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&runAi("ask")} placeholder="Ask about this group…"/><button onClick={()=>runAi("ask")} disabled={aiBusy}><Sparkles size={17}/></button></div></aside>
 </section></main>;
}